"""Generate icon.ico for the packaged .exe (PyInstaller's --icon flag).

Draws a small speedometer-style usage gauge -- green/yellow/red bands
plus a needle -- reusing the exact same color thresholds the floating
widget uses for its live percentage bars (WIDGET_COLORS / pct_tag() in
claude_usage_tray.py: green <50%, yellow <80%, red >=80%). The icon is
meant to look like a tiny picture of what the app actually shows, not
a generic placeholder shape.

PyInstaller needs a real .ico file on disk at build time -- there's no
way to bake a custom icon into the compiled .exe programmatically, so
this is a real (small) asset checked into the repo, regenerated by this
script whenever the design changes:

    python generate_icon.py
    pyinstaller --onefile --noconsole --icon=icon.ico --name ClaudeUsageTray claude_usage_tray.py
"""

import math

from PIL import Image, ImageDraw

GREEN = (95, 184, 95, 255)    # matches WIDGET_COLORS["green"] #5fb85f
YELLOW = (224, 179, 65, 255)  # matches WIDGET_COLORS["yellow"] #e0b341
RED = (224, 96, 90, 255)      # matches WIDGET_COLORS["red"] #e0605a
NEEDLE = (45, 42, 40, 255)

ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]
SUPERSAMPLE = 8

GAP_DEG = 90  # open span at the bottom of the gauge, like a real speedometer
NEEDLE_FRACTION = 0.62  # where the needle points, as a fraction of the full sweep


def draw_app_icon(size):
    s = size * SUPERSAMPLE
    img = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)

    margin = s * 0.06
    bbox = (margin, margin, s - margin, s - margin)
    cx = cy = s / 2
    r = (s - 2 * margin) / 2

    sweep = 360 - GAP_DEG
    start = 90 + GAP_DEG / 2  # Pillow angles: 0=east, 90=south, clockwise
    green_end = start + sweep * 0.50
    yellow_end = green_end + sweep * 0.30
    red_end = yellow_end + sweep * 0.20

    draw.pieslice(bbox, start, green_end, fill=GREEN)
    draw.pieslice(bbox, green_end, yellow_end, fill=YELLOW)
    draw.pieslice(bbox, yellow_end, red_end, fill=RED)

    # Punch a hole through the middle so the wedges read as a ring/gauge
    # face rather than a solid pie.
    hole_r = r * 0.55
    draw.ellipse((cx - hole_r, cy - hole_r, cx + hole_r, cy + hole_r), fill=(0, 0, 0, 0))

    needle_angle = math.radians(start + sweep * NEEDLE_FRACTION)
    needle_len = r * 0.98
    nx = cx + needle_len * math.cos(needle_angle)
    ny = cy + needle_len * math.sin(needle_angle)
    draw.line((cx, cy, nx, ny), fill=NEEDLE, width=max(1, round(s * 0.05)))

    pivot_r = s * 0.09
    draw.ellipse((cx - pivot_r, cy - pivot_r, cx + pivot_r, cy + pivot_r), fill=NEEDLE)

    return img.resize((size, size), Image.LANCZOS)


def main():
    base = draw_app_icon(256)
    base.save(
        "icon.ico",
        format="ICO",
        sizes=[(s, s) for s in ICO_SIZES],
    )
    print(f"Wrote icon.ico ({', '.join(f'{s}x{s}' for s in ICO_SIZES)})")


if __name__ == "__main__":
    main()
